spring.application.name=sage
spring.mvc.servlet.path=/api
spring.jpa.database=POSTGRESQL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.datasource.url=jdbc:postgresql://172.22.168.212:5432/sage
# spring.datasource.url=${DB_URL:jdbc:postgresql://172.27.207.162:5432/sage}
spring.datasource.username=${SQL_USERNAME:postgres}
spring.datasource.password=${SQL_PASSWORD:postgres}