spring.application.name=sage
spring.mvc.servlet.path=/api
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.datasource.url=${DB_URL}
spring.datasource.username=${SQL_USERNAME}
spring.datasource.password=${SQL_PASSWORD}
# spring.jpa.show-sql=true
# spring.datasource.url=jdbc:postgresql://localhost:5432/sage
# spring.datasource.username=postgres
# spring.datasource.password=postgres