// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: board.proto

package com.ft.board_controller_api.proto;

public final class BeatsProto {
  private BeatsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ft_board_controller_api_proto_BeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ft_board_controller_api_proto_BeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ft_board_controller_api_proto_BeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ft_board_controller_api_proto_BeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013board.proto\022!com.ft.board_controller_a" +
      "pi.proto\032\037google/protobuf/timestamp.prot" +
      "o\"d\n\013BeatRequest\022\020\n\010board_id\030\001 \001(\t\022\013\n\003bp" +
      "m\030\002 \001(\002\022\014\n\004spo2\030\003 \001(\002\022(\n\004time\030\004 \001(\0132\032.go" +
      "ogle.protobuf.Timestamp\"\016\n\014BeatResponse2" +
      "\200\001\n\rBoardServices\022o\n\nCreateBeat\022..com.ft" +
      ".board_controller_api.proto.BeatRequest\032" +
      "/.com.ft.board_controller_api.proto.Beat" +
      "Response\"\000B\026B\nBeatsProtoP\001\242\002\005BOARDb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_ft_board_controller_api_proto_BeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ft_board_controller_api_proto_BeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ft_board_controller_api_proto_BeatRequest_descriptor,
        new java.lang.String[] { "BoardId", "Bpm", "Spo2", "Time", });
    internal_static_com_ft_board_controller_api_proto_BeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ft_board_controller_api_proto_BeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ft_board_controller_api_proto_BeatResponse_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
