// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: board.proto

package com.ft.board_controller_api.proto;

public interface BeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ft.board_controller_api.proto.BeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * UUID
   * </pre>
   *
   * <code>string board_id = 1;</code>
   * @return The boardId.
   */
  java.lang.String getBoardId();
  /**
   * <pre>
   * UUID
   * </pre>
   *
   * <code>string board_id = 1;</code>
   * @return The bytes for boardId.
   */
  com.google.protobuf.ByteString
      getBoardIdBytes();

  /**
   * <code>float bpm = 2;</code>
   * @return The bpm.
   */
  float getBpm();

  /**
   * <code>float spo2 = 3;</code>
   * @return The spo2.
   */
  float getSpo2();

  /**
   * <code>.google.protobuf.Timestamp time = 4;</code>
   * @return Whether the time field is set.
   */
  boolean hasTime();
  /**
   * <code>.google.protobuf.Timestamp time = 4;</code>
   * @return The time.
   */
  com.google.protobuf.Timestamp getTime();
  /**
   * <code>.google.protobuf.Timestamp time = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();
}
