// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: board.proto

package com.ft.board_controller_api.proto;

/**
 * Protobuf type {@code com.ft.board_controller_api.proto.BeatRequest}
 */
public final class BeatRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ft.board_controller_api.proto.BeatRequest)
    BeatRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BeatRequest.newBuilder() to construct.
  private BeatRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BeatRequest() {
    boardId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BeatRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ft.board_controller_api.proto.BeatsProto.internal_static_com_ft_board_controller_api_proto_BeatRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ft.board_controller_api.proto.BeatsProto.internal_static_com_ft_board_controller_api_proto_BeatRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ft.board_controller_api.proto.BeatRequest.class, com.ft.board_controller_api.proto.BeatRequest.Builder.class);
  }

  public static final int BOARD_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object boardId_ = "";
  /**
   * <pre>
   * UUID
   * </pre>
   *
   * <code>string board_id = 1;</code>
   * @return The boardId.
   */
  @java.lang.Override
  public java.lang.String getBoardId() {
    java.lang.Object ref = boardId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      boardId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * UUID
   * </pre>
   *
   * <code>string board_id = 1;</code>
   * @return The bytes for boardId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBoardIdBytes() {
    java.lang.Object ref = boardId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      boardId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BPM_FIELD_NUMBER = 2;
  private float bpm_ = 0F;
  /**
   * <code>float bpm = 2;</code>
   * @return The bpm.
   */
  @java.lang.Override
  public float getBpm() {
    return bpm_;
  }

  public static final int SPO2_FIELD_NUMBER = 3;
  private float spo2_ = 0F;
  /**
   * <code>float spo2 = 3;</code>
   * @return The spo2.
   */
  @java.lang.Override
  public float getSpo2() {
    return spo2_;
  }

  public static final int TIME_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp time_;
  /**
   * <code>.google.protobuf.Timestamp time = 4;</code>
   * @return Whether the time field is set.
   */
  @java.lang.Override
  public boolean hasTime() {
    return time_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp time = 4;</code>
   * @return The time.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTime() {
    return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
  }
  /**
   * <code>.google.protobuf.Timestamp time = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
    return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(boardId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, boardId_);
    }
    if (java.lang.Float.floatToRawIntBits(bpm_) != 0) {
      output.writeFloat(2, bpm_);
    }
    if (java.lang.Float.floatToRawIntBits(spo2_) != 0) {
      output.writeFloat(3, spo2_);
    }
    if (time_ != null) {
      output.writeMessage(4, getTime());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(boardId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, boardId_);
    }
    if (java.lang.Float.floatToRawIntBits(bpm_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, bpm_);
    }
    if (java.lang.Float.floatToRawIntBits(spo2_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, spo2_);
    }
    if (time_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getTime());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ft.board_controller_api.proto.BeatRequest)) {
      return super.equals(obj);
    }
    com.ft.board_controller_api.proto.BeatRequest other = (com.ft.board_controller_api.proto.BeatRequest) obj;

    if (!getBoardId()
        .equals(other.getBoardId())) return false;
    if (java.lang.Float.floatToIntBits(getBpm())
        != java.lang.Float.floatToIntBits(
            other.getBpm())) return false;
    if (java.lang.Float.floatToIntBits(getSpo2())
        != java.lang.Float.floatToIntBits(
            other.getSpo2())) return false;
    if (hasTime() != other.hasTime()) return false;
    if (hasTime()) {
      if (!getTime()
          .equals(other.getTime())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOARD_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBoardId().hashCode();
    hash = (37 * hash) + BPM_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getBpm());
    hash = (37 * hash) + SPO2_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getSpo2());
    if (hasTime()) {
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ft.board_controller_api.proto.BeatRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ft.board_controller_api.proto.BeatRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ft.board_controller_api.proto.BeatRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ft.board_controller_api.proto.BeatRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ft.board_controller_api.proto.BeatRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ft.board_controller_api.proto.BeatRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ft.board_controller_api.proto.BeatRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ft.board_controller_api.proto.BeatRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ft.board_controller_api.proto.BeatRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ft.board_controller_api.proto.BeatRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ft.board_controller_api.proto.BeatRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ft.board_controller_api.proto.BeatRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ft.board_controller_api.proto.BeatRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ft.board_controller_api.proto.BeatRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ft.board_controller_api.proto.BeatRequest)
      com.ft.board_controller_api.proto.BeatRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ft.board_controller_api.proto.BeatsProto.internal_static_com_ft_board_controller_api_proto_BeatRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ft.board_controller_api.proto.BeatsProto.internal_static_com_ft_board_controller_api_proto_BeatRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ft.board_controller_api.proto.BeatRequest.class, com.ft.board_controller_api.proto.BeatRequest.Builder.class);
    }

    // Construct using com.ft.board_controller_api.proto.BeatRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      boardId_ = "";
      bpm_ = 0F;
      spo2_ = 0F;
      time_ = null;
      if (timeBuilder_ != null) {
        timeBuilder_.dispose();
        timeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ft.board_controller_api.proto.BeatsProto.internal_static_com_ft_board_controller_api_proto_BeatRequest_descriptor;
    }

    @java.lang.Override
    public com.ft.board_controller_api.proto.BeatRequest getDefaultInstanceForType() {
      return com.ft.board_controller_api.proto.BeatRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ft.board_controller_api.proto.BeatRequest build() {
      com.ft.board_controller_api.proto.BeatRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ft.board_controller_api.proto.BeatRequest buildPartial() {
      com.ft.board_controller_api.proto.BeatRequest result = new com.ft.board_controller_api.proto.BeatRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ft.board_controller_api.proto.BeatRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.boardId_ = boardId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.bpm_ = bpm_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.spo2_ = spo2_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.time_ = timeBuilder_ == null
            ? time_
            : timeBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ft.board_controller_api.proto.BeatRequest) {
        return mergeFrom((com.ft.board_controller_api.proto.BeatRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ft.board_controller_api.proto.BeatRequest other) {
      if (other == com.ft.board_controller_api.proto.BeatRequest.getDefaultInstance()) return this;
      if (!other.getBoardId().isEmpty()) {
        boardId_ = other.boardId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getBpm() != 0F) {
        setBpm(other.getBpm());
      }
      if (other.getSpo2() != 0F) {
        setSpo2(other.getSpo2());
      }
      if (other.hasTime()) {
        mergeTime(other.getTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              boardId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 21: {
              bpm_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              spo2_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 34: {
              input.readMessage(
                  getTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object boardId_ = "";
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>string board_id = 1;</code>
     * @return The boardId.
     */
    public java.lang.String getBoardId() {
      java.lang.Object ref = boardId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        boardId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>string board_id = 1;</code>
     * @return The bytes for boardId.
     */
    public com.google.protobuf.ByteString
        getBoardIdBytes() {
      java.lang.Object ref = boardId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        boardId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>string board_id = 1;</code>
     * @param value The boardId to set.
     * @return This builder for chaining.
     */
    public Builder setBoardId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      boardId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>string board_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBoardId() {
      boardId_ = getDefaultInstance().getBoardId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>string board_id = 1;</code>
     * @param value The bytes for boardId to set.
     * @return This builder for chaining.
     */
    public Builder setBoardIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      boardId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private float bpm_ ;
    /**
     * <code>float bpm = 2;</code>
     * @return The bpm.
     */
    @java.lang.Override
    public float getBpm() {
      return bpm_;
    }
    /**
     * <code>float bpm = 2;</code>
     * @param value The bpm to set.
     * @return This builder for chaining.
     */
    public Builder setBpm(float value) {
      
      bpm_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float bpm = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBpm() {
      bitField0_ = (bitField0_ & ~0x00000002);
      bpm_ = 0F;
      onChanged();
      return this;
    }

    private float spo2_ ;
    /**
     * <code>float spo2 = 3;</code>
     * @return The spo2.
     */
    @java.lang.Override
    public float getSpo2() {
      return spo2_;
    }
    /**
     * <code>float spo2 = 3;</code>
     * @param value The spo2 to set.
     * @return This builder for chaining.
     */
    public Builder setSpo2(float value) {
      
      spo2_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float spo2 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpo2() {
      bitField0_ = (bitField0_ & ~0x00000004);
      spo2_ = 0F;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp time_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp time = 4;</code>
     * @return Whether the time field is set.
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4;</code>
     * @return The time.
     */
    public com.google.protobuf.Timestamp getTime() {
      if (timeBuilder_ == null) {
        return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
      } else {
        return timeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4;</code>
     */
    public Builder setTime(com.google.protobuf.Timestamp value) {
      if (timeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        time_ = value;
      } else {
        timeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4;</code>
     */
    public Builder setTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timeBuilder_ == null) {
        time_ = builderForValue.build();
      } else {
        timeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4;</code>
     */
    public Builder mergeTime(com.google.protobuf.Timestamp value) {
      if (timeBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          time_ != null &&
          time_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimeBuilder().mergeFrom(value);
        } else {
          time_ = value;
        }
      } else {
        timeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4;</code>
     */
    public Builder clearTime() {
      bitField0_ = (bitField0_ & ~0x00000008);
      time_ = null;
      if (timeBuilder_ != null) {
        timeBuilder_.dispose();
        timeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimeBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
      if (timeBuilder_ != null) {
        return timeBuilder_.getMessageOrBuilder();
      } else {
        return time_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : time_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp time = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimeFieldBuilder() {
      if (timeBuilder_ == null) {
        timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTime(),
                getParentForChildren(),
                isClean());
        time_ = null;
      }
      return timeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ft.board_controller_api.proto.BeatRequest)
  }

  // @@protoc_insertion_point(class_scope:com.ft.board_controller_api.proto.BeatRequest)
  private static final com.ft.board_controller_api.proto.BeatRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ft.board_controller_api.proto.BeatRequest();
  }

  public static com.ft.board_controller_api.proto.BeatRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BeatRequest>
      PARSER = new com.google.protobuf.AbstractParser<BeatRequest>() {
    @java.lang.Override
    public BeatRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BeatRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BeatRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ft.board_controller_api.proto.BeatRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

