// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: board.proto

package com.ft.board_controller_api.proto;

public interface BeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ft.board_controller_api.proto.BeatResponse)
    com.google.protobuf.MessageOrBuilder {
}
