name: board-controller-api-deploy

on:
  push:
    branches:
      - main

jobs:
  creqate-artifact-register-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/modules/artifact-registry

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Google auth"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.11.1

      - name: Terraform Init
        run: terraform init

      - name: Terraform plan artifact registry
        run: terraform plan -var project_id='${{ secrets.PROJECT_ID }}' -auto-approve
